# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14p8UbV4n9esNxIJPiUNb-O8fXTIBLle1
"""

# Regression

import pandas as pd

df=pd.read_csv('/content/FuelConsumption.csv')
df.head(10)

df.describe()

cdf=df[['ENGINESIZE','CYLINDERS','FUELCONSUMPTION_CITY','FUELCONSUMPTION_HWY','FUELCONSUMPTION_COMB','FUELCONSUMPTION_COMB_MPG','CO2EMISSIONS']]
cdf.tail(10)

import matplotlib.pyplot as plt
viz=cdf[['CO2EMISSIONS','FUELCONSUMPTION_CITY','CYLINDERS','ENGINESIZE']]
viz.hist()
plt.show()

plt.scatter(df.ENGINESIZE,df.CO2EMISSIONS,color='blue')
plt.xlabel('ENGINESIZE')
plt.ylabel('CO2EMISSION')
plt.title('EMISION')

import numpy as np
msk=np.random.rand(len(df))<0.8
train=cdf[msk]
test=cdf[~msk]
print(msk)
print(~msk)
print(train)
print(test)

plt.scatter(train.CYLINDERS,train.CO2EMISSIONS,color='red')
plt.xlabel('CYLINDERS')
plt.ylabel('CO2EMISSIONS')
plt.title('train')
plt.show()

fig=plt.figure()
ax1=fig.add_subplot(111)
ax1.scatter(train.ENGINESIZE,train.CO2EMISSIONS,color='blue',label='train')
ax1.scatter(test.ENGINESIZE,test.CO2EMISSIONS,color='red',label='test')
ax1.legend(('train','test'),loc='upper right')
plt.xlabel('ENIGINESIZE')
plt.ylabel('CO2EMISSIONS')
plt.show()

from sklearn import linear_model
regr=linear_model.LinearRegression()
train_x=np.asanyarray(train[['ENGINESIZE']])
train_y=np.asanyarray(train[['CO2EMISSIONS']])
regr.fit(train_x,train_y)
print('Coefficient:',regr.coef_)
print('Intercept:',regr.intercept_)

plt.scatter(train.ENGINESIZE,train.CO2EMISSIONS,color='blue')
plt.plot(train_x,regr.coef_[0][0]*train_x+regr.intercept_[0],color='red')

from sklearn.metrics import r2_score
test_x=np.asanyarray(test[['ENGINESIZE']])
test_y=np.asanyarray(test[['CO2EMISSIONS']])
test_y_=regr.predict(test_x)
print('Mean absolute error:%.2f' % np.mean(np.absolute(test_y_-test_y)))
print('Residual sum of squares (MSE):%.2f' % np.mean((test_y_-test_y)**2))
print('R2_score:%.2f' %r2_score(test_y,test_y_) )